//! Unicode character properties, with Unicode 18 changes overlaid on the
//! ICU4X 2.1 bundled data.
//!
//! The overlay tables were generated by comparing `icu_properties` 2.1.2 with
//! 2.3.0 plus `icu_properties_data` from unicode-org/icu4x at
//! d1bf2f27ddeabbb61ee50f7cf1dac151aaa0d692 (Unicode 18.0.0).
//! Remove the tables when a released ICU4X data crate contains Unicode 18.

use icu_properties::{
    CodePointMapData, PropertyNamesShort,
    props::{BidiClass, GeneralCategory, Script},
    script::ScriptWithExtensions,
};
use smallvec::SmallVec;
use tinystr::{TinyAsciiStr, tinystr};

pub const VERSION: (u8, u8, u8) = (18, 0, 0);

/// A four-letter ISO 15924 script code, e.g. "Latn"
pub type UnicodeShortName = TinyAsciiStr<4>;

type Range<T> = (u32, u32, T);

fn lookup<T: Copy>(cp: u32, ranges: &'static [Range<T>]) -> Option<T> {
    let index = ranges.partition_point(|(start, _, _)| *start <= cp);
    let (_, end, value) = ranges.get(index.checked_sub(1)?)?;
    (cp <= *end).then_some(*value)
}

const SCRIPT: &[Range<UnicodeShortName>] = &[
    (0x0558, 0x0558, tinystr!(4, "Armn")),
    (0x058B, 0x058C, tinystr!(4, "Armn")),
    (0x05C8, 0x05C9, tinystr!(4, "Hebr")),
    (0x0B53, 0x0B54, tinystr!(4, "Orya")),
    (0x1ADE, 0x1ADF, tinystr!(4, "Zinh")),
    (0x1AEC, 0x1AF0, tinystr!(4, "Zinh")),
    (0x208F, 0x208F, tinystr!(4, "Zyyy")),
    (0x209D, 0x209F, tinystr!(4, "Latn")),
    (0x20C2, 0x20C4, tinystr!(4, "Zyyy")),
    (0x2E60, 0x2E63, tinystr!(4, "Zyyy")),
    (0xA7DD, 0xA7DD, tinystr!(4, "Latn")),
    (0xA7E2, 0xA7E2, tinystr!(4, "Latn")),
    (0xAB6C, 0xAB6D, tinystr!(4, "Latn")),
    (0x107BB, 0x107BF, tinystr!(4, "Latn")),
    (0x10EC9, 0x10ECF, tinystr!(4, "Arab")),
    (0x10ED9, 0x10EEE, tinystr!(4, "Arab")),
    (0x10EF0, 0x10EF9, tinystr!(4, "Arab")),
    (0x11B0A, 0x11B0A, tinystr!(4, "Deva")),
    (0x11DF0, 0x11DF1, tinystr!(4, "Beng")),
    (0x1246F, 0x1246F, tinystr!(4, "Xsux")),
    (0x12475, 0x1247F, tinystr!(4, "Xsux")),
    (0x12550, 0x125A7, tinystr!(4, "Xsux")),
    (0x125A8, 0x1264B, tinystr!(4, "Pcun")),
    (0x1264C, 0x12686, tinystr!(4, "Xsux")),
    (0x18CD6, 0x18CDA, tinystr!(4, "Kits")),
    (0x18D1F, 0x18D20, tinystr!(4, "Tang")),
    (0x18E00, 0x19191, tinystr!(4, "Jurc")),
    (0x191A0, 0x191D2, tinystr!(4, "Jurc")),
    (0x1B123, 0x1B123, tinystr!(4, "Hira")),
    (0x1B124, 0x1B128, tinystr!(4, "Kana")),
    (0x1B168, 0x1B168, tinystr!(4, "Kana")),
    (0x1CED2, 0x1CED4, tinystr!(4, "Zyyy")),
    (0x1CEDD, 0x1CEDF, tinystr!(4, "Zyyy")),
    (0x1CEF1, 0x1CEFD, tinystr!(4, "Zyyy")),
    (0x1D127, 0x1D128, tinystr!(4, "Zinh")),
    (0x1D1EB, 0x1D1FF, tinystr!(4, "Zyyy")),
    (0x1D250, 0x1D25A, tinystr!(4, "Zyyy")),
    (0x1D25B, 0x1D25C, tinystr!(4, "Zinh")),
    (0x1D25D, 0x1D281, tinystr!(4, "Zyyy")),
    (0x1D6A6, 0x1D6A6, tinystr!(4, "Zyyy")),
    (0x1DB00, 0x1DB1C, tinystr!(4, "Zyyy")),
    (0x1DF1F, 0x1DF24, tinystr!(4, "Latn")),
    (0x1DF2B, 0x1DF81, tinystr!(4, "Latn")),
    (0x1DF90, 0x1DF96, tinystr!(4, "Latn")),
    (0x1DFCD, 0x1DFF2, tinystr!(4, "Latn")),
    (0x1DFF3, 0x1DFF4, tinystr!(4, "Grek")),
    (0x1DFF5, 0x1DFFF, tinystr!(4, "Latn")),
    (0x1F1AE, 0x1F1AE, tinystr!(4, "Zyyy")),
    (0x1F6D9, 0x1F6D9, tinystr!(4, "Zyyy")),
    (0x1F7DA, 0x1F7DB, tinystr!(4, "Zyyy")),
    (0x1F7F1, 0x1F7FF, tinystr!(4, "Zyyy")),
    (0x1FA8B, 0x1FA8D, tinystr!(4, "Zyyy")),
    (0x1FACC, 0x1FACC, tinystr!(4, "Zyyy")),
    (0x1FADD, 0x1FADD, tinystr!(4, "Zyyy")),
    (0x1FAEB, 0x1FAEB, tinystr!(4, "Zyyy")),
    (0x1FAF9, 0x1FAFA, tinystr!(4, "Zyyy")),
    (0x2B81E, 0x2B81E, tinystr!(4, "Hani")),
    (0x3D000, 0x3FC3F, tinystr!(4, "Seal")),
];

const SCRIPT_EXTENSIONS: &[Range<&[UnicodeShortName]>] = &[
    (0x0558, 0x0558, &[tinystr!(4, "Armn")]),
    (0x058B, 0x058C, &[tinystr!(4, "Armn")]),
    (0x05C8, 0x05C9, &[tinystr!(4, "Hebr")]),
    (0x0B53, 0x0B54, &[tinystr!(4, "Orya")]),
    (
        0x0B83,
        0x0B83,
        &[
            tinystr!(4, "Knda"),
            tinystr!(4, "Mlym"),
            tinystr!(4, "Taml"),
            tinystr!(4, "Telu"),
        ],
    ),
    (0x1ADE, 0x1ADF, &[tinystr!(4, "Zinh")]),
    (0x1AEC, 0x1AF0, &[tinystr!(4, "Zinh")]),
    (0x1CF5, 0x1CF6, &[tinystr!(4, "Beng")]),
    (0x208F, 0x208F, &[tinystr!(4, "Zyyy")]),
    (0x209D, 0x209F, &[tinystr!(4, "Latn")]),
    (0x20C2, 0x20C4, &[tinystr!(4, "Zyyy")]),
    (0x2E60, 0x2E63, &[tinystr!(4, "Zyyy")]),
    (0xA7DD, 0xA7DD, &[tinystr!(4, "Latn")]),
    (0xA7E2, 0xA7E2, &[tinystr!(4, "Latn")]),
    (0xAB6C, 0xAB6D, &[tinystr!(4, "Latn")]),
    (0x107BB, 0x107BF, &[tinystr!(4, "Latn")]),
    (0x10EC9, 0x10ECF, &[tinystr!(4, "Arab")]),
    (0x10ED9, 0x10EEE, &[tinystr!(4, "Arab")]),
    (0x10EF0, 0x10EF9, &[tinystr!(4, "Arab")]),
    (0x11B0A, 0x11B0A, &[tinystr!(4, "Deva")]),
    (0x11DF0, 0x11DF1, &[tinystr!(4, "Beng")]),
    (0x1246F, 0x1246F, &[tinystr!(4, "Xsux")]),
    (0x12475, 0x1247F, &[tinystr!(4, "Xsux")]),
    (
        0x12550,
        0x12586,
        &[tinystr!(4, "Pcun"), tinystr!(4, "Xsux")],
    ),
    (0x12587, 0x1258B, &[tinystr!(4, "Xsux")]),
    (
        0x1258C,
        0x1258D,
        &[tinystr!(4, "Pcun"), tinystr!(4, "Xsux")],
    ),
    (0x1258E, 0x12599, &[tinystr!(4, "Xsux")]),
    (
        0x1259A,
        0x125A7,
        &[tinystr!(4, "Pcun"), tinystr!(4, "Xsux")],
    ),
    (0x125A8, 0x1264B, &[tinystr!(4, "Pcun")]),
    (0x1264C, 0x12686, &[tinystr!(4, "Xsux")]),
    (0x18CD6, 0x18CDA, &[tinystr!(4, "Kits")]),
    (0x18D1F, 0x18D20, &[tinystr!(4, "Tang")]),
    (0x18E00, 0x19191, &[tinystr!(4, "Jurc")]),
    (0x191A0, 0x191D2, &[tinystr!(4, "Jurc")]),
    (0x1B123, 0x1B123, &[tinystr!(4, "Hira")]),
    (0x1B124, 0x1B128, &[tinystr!(4, "Kana")]),
    (0x1B168, 0x1B168, &[tinystr!(4, "Kana")]),
    (0x1CED2, 0x1CED4, &[tinystr!(4, "Zyyy")]),
    (0x1CEDD, 0x1CEDF, &[tinystr!(4, "Zyyy")]),
    (0x1CEF1, 0x1CEFD, &[tinystr!(4, "Zyyy")]),
    (0x1D127, 0x1D128, &[tinystr!(4, "Zinh")]),
    (0x1D1EB, 0x1D1FF, &[tinystr!(4, "Zyyy")]),
    (0x1D250, 0x1D25A, &[tinystr!(4, "Zyyy")]),
    (0x1D25B, 0x1D25C, &[tinystr!(4, "Zinh")]),
    (0x1D25D, 0x1D281, &[tinystr!(4, "Zyyy")]),
    (0x1D6A6, 0x1D6A6, &[tinystr!(4, "Zyyy")]),
    (0x1DB00, 0x1DB1C, &[tinystr!(4, "Zyyy")]),
    (0x1DF1F, 0x1DF24, &[tinystr!(4, "Latn")]),
    (0x1DF2B, 0x1DF81, &[tinystr!(4, "Latn")]),
    (0x1DF90, 0x1DF96, &[tinystr!(4, "Latn")]),
    (0x1DFCD, 0x1DFF2, &[tinystr!(4, "Latn")]),
    (0x1DFF3, 0x1DFF4, &[tinystr!(4, "Grek")]),
    (0x1DFF5, 0x1DFFF, &[tinystr!(4, "Latn")]),
    (0x1F1AE, 0x1F1AE, &[tinystr!(4, "Zyyy")]),
    (0x1F6D9, 0x1F6D9, &[tinystr!(4, "Zyyy")]),
    (0x1F7DA, 0x1F7DB, &[tinystr!(4, "Zyyy")]),
    (0x1F7F1, 0x1F7FF, &[tinystr!(4, "Zyyy")]),
    (0x1FA8B, 0x1FA8D, &[tinystr!(4, "Zyyy")]),
    (0x1FACC, 0x1FACC, &[tinystr!(4, "Zyyy")]),
    (0x1FADD, 0x1FADD, &[tinystr!(4, "Zyyy")]),
    (0x1FAEB, 0x1FAEB, &[tinystr!(4, "Zyyy")]),
    (0x1FAF9, 0x1FAFA, &[tinystr!(4, "Zyyy")]),
    (0x2B81E, 0x2B81E, &[tinystr!(4, "Hani")]),
    (0x3D000, 0x3FC3F, &[tinystr!(4, "Seal")]),
];

const GENERAL_CATEGORY: &[Range<GeneralCategory>] = &[
    (0x0558, 0x0558, GeneralCategory::ModifierLetter),
    (0x058B, 0x058C, GeneralCategory::ModifierLetter),
    (0x05C8, 0x05C9, GeneralCategory::NonspacingMark),
    (0x0B53, 0x0B54, GeneralCategory::NonspacingMark),
    (0x1ADE, 0x1ADF, GeneralCategory::NonspacingMark),
    (0x1AEC, 0x1AF0, GeneralCategory::NonspacingMark),
    (0x208F, 0x208F, GeneralCategory::ModifierLetter),
    (0x209D, 0x209F, GeneralCategory::ModifierLetter),
    (0x20C2, 0x20C4, GeneralCategory::CurrencySymbol),
    (0x2E60, 0x2E61, GeneralCategory::OtherPunctuation),
    (0x2E62, 0x2E62, GeneralCategory::OpenPunctuation),
    (0x2E63, 0x2E63, GeneralCategory::ClosePunctuation),
    (0xA7DD, 0xA7DD, GeneralCategory::UppercaseLetter),
    (0xA7E2, 0xA7E2, GeneralCategory::UppercaseLetter),
    (0xAB6C, 0xAB6D, GeneralCategory::UppercaseLetter),
    (0x107BB, 0x107BF, GeneralCategory::ModifierLetter),
    (0x10EC9, 0x10ECA, GeneralCategory::ModifierSymbol),
    (0x10ECB, 0x10ECF, GeneralCategory::NonspacingMark),
    (0x10ED9, 0x10EEE, GeneralCategory::OtherLetter),
    (0x10EF0, 0x10EF9, GeneralCategory::NonspacingMark),
    (0x11B0A, 0x11B0A, GeneralCategory::OtherLetter),
    (0x11DF0, 0x11DF0, GeneralCategory::NonspacingMark),
    (0x11DF1, 0x11DF1, GeneralCategory::OtherLetter),
    (0x1246F, 0x1246F, GeneralCategory::LetterNumber),
    (0x12475, 0x1247F, GeneralCategory::LetterNumber),
    (0x12550, 0x12686, GeneralCategory::LetterNumber),
    (0x18CD6, 0x18CDA, GeneralCategory::OtherLetter),
    (0x18D1F, 0x18D20, GeneralCategory::OtherLetter),
    (0x18E00, 0x19191, GeneralCategory::OtherLetter),
    (0x191A0, 0x191D2, GeneralCategory::OtherLetter),
    (0x1B123, 0x1B128, GeneralCategory::OtherLetter),
    (0x1B168, 0x1B168, GeneralCategory::OtherLetter),
    (0x1CED2, 0x1CED4, GeneralCategory::OtherSymbol),
    (0x1CEDD, 0x1CEDF, GeneralCategory::MathSymbol),
    (0x1CEF1, 0x1CEFD, GeneralCategory::MathSymbol),
    (0x1D127, 0x1D128, GeneralCategory::NonspacingMark),
    (0x1D1EB, 0x1D1FF, GeneralCategory::OtherSymbol),
    (0x1D250, 0x1D252, GeneralCategory::SpacingMark),
    (0x1D253, 0x1D25A, GeneralCategory::OtherSymbol),
    (0x1D25B, 0x1D25C, GeneralCategory::NonspacingMark),
    (0x1D25D, 0x1D25E, GeneralCategory::OtherSymbol),
    (0x1D25F, 0x1D25F, GeneralCategory::SpacingMark),
    (0x1D260, 0x1D27F, GeneralCategory::OtherSymbol),
    (0x1D280, 0x1D281, GeneralCategory::SpacingMark),
    (0x1D6A6, 0x1D6A6, GeneralCategory::LowercaseLetter),
    (0x1DB00, 0x1DB1C, GeneralCategory::MathSymbol),
    (0x1DF1F, 0x1DF24, GeneralCategory::LowercaseLetter),
    (0x1DF2B, 0x1DF3F, GeneralCategory::LowercaseLetter),
    (0x1DF40, 0x1DF40, GeneralCategory::UppercaseLetter),
    (0x1DF41, 0x1DF47, GeneralCategory::LowercaseLetter),
    (0x1DF48, 0x1DF48, GeneralCategory::UppercaseLetter),
    (0x1DF49, 0x1DF49, GeneralCategory::LowercaseLetter),
    (0x1DF4A, 0x1DF4A, GeneralCategory::UppercaseLetter),
    (0x1DF4B, 0x1DF4C, GeneralCategory::LowercaseLetter),
    (0x1DF4D, 0x1DF4D, GeneralCategory::UppercaseLetter),
    (0x1DF4E, 0x1DF50, GeneralCategory::LowercaseLetter),
    (0x1DF51, 0x1DF51, GeneralCategory::UppercaseLetter),
    (0x1DF52, 0x1DF67, GeneralCategory::LowercaseLetter),
    (0x1DF68, 0x1DF68, GeneralCategory::UppercaseLetter),
    (0x1DF69, 0x1DF69, GeneralCategory::LowercaseLetter),
    (0x1DF6A, 0x1DF6A, GeneralCategory::UppercaseLetter),
    (0x1DF6B, 0x1DF6B, GeneralCategory::LowercaseLetter),
    (0x1DF6C, 0x1DF6C, GeneralCategory::UppercaseLetter),
    (0x1DF6D, 0x1DF6D, GeneralCategory::LowercaseLetter),
    (0x1DF6E, 0x1DF6E, GeneralCategory::UppercaseLetter),
    (0x1DF6F, 0x1DF71, GeneralCategory::LowercaseLetter),
    (0x1DF72, 0x1DF72, GeneralCategory::UppercaseLetter),
    (0x1DF73, 0x1DF73, GeneralCategory::LowercaseLetter),
    (0x1DF74, 0x1DF74, GeneralCategory::UppercaseLetter),
    (0x1DF75, 0x1DF75, GeneralCategory::LowercaseLetter),
    (0x1DF76, 0x1DF76, GeneralCategory::UppercaseLetter),
    (0x1DF77, 0x1DF77, GeneralCategory::LowercaseLetter),
    (0x1DF78, 0x1DF78, GeneralCategory::UppercaseLetter),
    (0x1DF79, 0x1DF79, GeneralCategory::LowercaseLetter),
    (0x1DF7A, 0x1DF7A, GeneralCategory::UppercaseLetter),
    (0x1DF7B, 0x1DF7B, GeneralCategory::LowercaseLetter),
    (0x1DF7C, 0x1DF7C, GeneralCategory::UppercaseLetter),
    (0x1DF7D, 0x1DF7D, GeneralCategory::LowercaseLetter),
    (0x1DF7E, 0x1DF7E, GeneralCategory::UppercaseLetter),
    (0x1DF7F, 0x1DF7F, GeneralCategory::LowercaseLetter),
    (0x1DF80, 0x1DF81, GeneralCategory::OtherLetter),
    (0x1DF90, 0x1DF96, GeneralCategory::LowercaseLetter),
    (0x1DFCD, 0x1DFFF, GeneralCategory::ModifierLetter),
    (0x1F1AE, 0x1F1AE, GeneralCategory::OtherSymbol),
    (0x1F6D9, 0x1F6D9, GeneralCategory::OtherSymbol),
    (0x1F7DA, 0x1F7DB, GeneralCategory::OtherSymbol),
    (0x1F7F1, 0x1F7FF, GeneralCategory::OtherSymbol),
    (0x1FA8B, 0x1FA8D, GeneralCategory::OtherSymbol),
    (0x1FACC, 0x1FACC, GeneralCategory::OtherSymbol),
    (0x1FADD, 0x1FADD, GeneralCategory::OtherSymbol),
    (0x1FAEB, 0x1FAEB, GeneralCategory::OtherSymbol),
    (0x1FAF9, 0x1FAFA, GeneralCategory::OtherSymbol),
    (0x2B81E, 0x2B81E, GeneralCategory::OtherLetter),
    (0x3D000, 0x3FC3F, GeneralCategory::OtherLetter),
];

const BIDI_CLASS: &[Range<BidiClass>] = &[
    (0x05C8, 0x05C9, BidiClass::NonspacingMark),
    (0x0B53, 0x0B54, BidiClass::NonspacingMark),
    (0x1ADE, 0x1ADF, BidiClass::NonspacingMark),
    (0x1AEC, 0x1AF0, BidiClass::NonspacingMark),
    (0x1B3A, 0x1B3A, BidiClass::LeftToRight),
    (0x1B3C, 0x1B3C, BidiClass::LeftToRight),
    (0x1B42, 0x1B42, BidiClass::LeftToRight),
    (0x208F, 0x208F, BidiClass::OtherNeutral),
    (0x2E60, 0x2E63, BidiClass::OtherNeutral),
    (0x10ECB, 0x10ECF, BidiClass::NonspacingMark),
    (0x10EF0, 0x10EF9, BidiClass::NonspacingMark),
    (0x11DF0, 0x11DF0, BidiClass::NonspacingMark),
    (0x1CED2, 0x1CED4, BidiClass::OtherNeutral),
    (0x1CEDD, 0x1CEDF, BidiClass::OtherNeutral),
    (0x1CEF1, 0x1CEFD, BidiClass::OtherNeutral),
    (0x1D127, 0x1D128, BidiClass::NonspacingMark),
    (0x1D25B, 0x1D25C, BidiClass::NonspacingMark),
    (0x1DB00, 0x1DB1C, BidiClass::OtherNeutral),
    (0x1F6D9, 0x1F6D9, BidiClass::OtherNeutral),
    (0x1F7DB, 0x1F7DB, BidiClass::OtherNeutral),
    (0x1F7F1, 0x1F7FF, BidiClass::OtherNeutral),
    (0x1FA8B, 0x1FA8D, BidiClass::OtherNeutral),
    (0x1FACC, 0x1FACC, BidiClass::OtherNeutral),
    (0x1FADD, 0x1FADD, BidiClass::OtherNeutral),
    (0x1FAEB, 0x1FAEB, BidiClass::OtherNeutral),
    (0x1FAF9, 0x1FAFA, BidiClass::OtherNeutral),
];

/// The Script property of this code point
pub fn script(cp: u32) -> Option<UnicodeShortName> {
    lookup(cp, SCRIPT)
        .or_else(|| script_short_name(ScriptWithExtensions::new().get_script_val32(cp)))
}

/// The Script_Extensions property of this code point
pub fn script_extensions(cp: u32) -> SmallVec<[UnicodeShortName; 4]> {
    match lookup(cp, SCRIPT_EXTENSIONS) {
        Some(scripts) => scripts.into(),
        None => ScriptWithExtensions::new()
            .get_script_extensions_val32(cp)
            .iter()
            .filter_map(script_short_name)
            .collect(),
    }
}

/// The General_Category property of this character
pub fn general_category(c: char) -> GeneralCategory {
    lookup(c as u32, GENERAL_CATEGORY)
        .unwrap_or_else(|| CodePointMapData::<GeneralCategory>::new().get(c))
}

/// The Bidi_Class property of this code point
pub fn bidi_class(cp: u32) -> BidiClass {
    lookup(cp, BIDI_CLASS).unwrap_or_else(|| CodePointMapData::<BidiClass>::new().get32(cp))
}

/// Whether this is a script added in Unicode 18, unknown to ICU4X 2.1
pub fn is_new_script(script: UnicodeShortName) -> bool {
    matches!(script.as_str(), "Jurc" | "Pcun" | "Seal")
}

/// The four-letter short name of this ICU script
pub fn script_short_name(script: Script) -> Option<UnicodeShortName> {
    PropertyNamesShort::<Script>::new()
        .get(script)
        .and_then(|name| UnicodeShortName::try_from_str(name).ok())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ranges_are_sorted_and_nonoverlapping() {
        fn check<T>(ranges: &[Range<T>]) {
            assert!(
                ranges
                    .windows(2)
                    .all(|window| matches!(window, [first, second] if first.1 < second.0))
            );
        }
        check(SCRIPT);
        check(SCRIPT_EXTENSIONS);
        check(GENERAL_CATEGORY);
        check(BIDI_CLASS);
    }
}
