//! The result of a compilation

use std::collections::{BTreeMap, HashMap};

use smol_str::SmolStr;
use write_fonts::{
    BuilderError, FontBuilder,
    tables::{
        self as wtables,
        gdef::GlyphClassDef,
        layout::{
            ConditionSet, FeatureParams, FeatureVariations,
            builders::CaretValueBuilder as CaretValue,
        },
        maxp::Maxp,
        stat::AxisValue,
        variations::{common_builder::RemapVarStore, ivs_builder::VariationStoreBuilder},
    },
    types::{GlyphId16, NameId, Tag},
};

use super::Opts;
use super::feature_writer::InsertionPoint;
use super::tables::DEBG_TAG;

use crate::{
    Diagnostic, DiagnosticSet, GlyphMap, GlyphSet, ParseTree,
    common::MarkClass,
    compile::{
        FeatureBuilder, FeatureProvider,
        features::{AllFeatures, ConditionSetMap},
        language_system::DefaultLanguageSystems,
        lookups::{AllLookups, FilterSetId},
        tables::Tables,
    },
};

/// The raw state after compiling one FEA source, before running a feature
/// provider (if present) and before finalizing.
///
/// This exists to support the case of merging two or more different non-variable
/// FEA sources into a variable output, in the vein of python's varLib.
#[derive(Debug)]
pub struct PendingCompilation {
    pub(super) tree: ParseTree,
    pub(super) features: AllFeatures,
    pub(super) lookups: AllLookups,
    pub(super) tables: Tables,
    pub(super) default_lang_systems: DefaultLanguageSystems,
    pub(super) conditionset_defs: ConditionSetMap,
    pub(super) insert_markers: HashMap<Tag, InsertionPoint>,
    pub(super) mark_filter_sets: HashMap<GlyphSet, FilterSetId>,
    pub(super) mark_classes: HashMap<SmolStr, MarkClass>,
    pub(super) mark_attach_class_id: HashMap<GlyphSet, u16>,
    pub(super) errors: Vec<Diagnostic>,
    pub(super) opts: Opts,
    pub(super) lig_carets_from_feature_writer: BTreeMap<GlyphId16, Vec<CaretValue>>,
    pub(super) axis_count: u16,
}

/// The tables generated by this compilation.
///
/// All tables are optional, and the set of tables that are present depends
/// on the input file.
///
/// Each table is a type defined in the [`write-fonts`][] crate. The caller
/// may either interact with these directly, or else they may use the [`to_binary`]
/// method to generate a binary font.
///
/// [`to_binary`]: Compilation::to_binary
/// [`write-fonts`]: https://docs.rs/write-fonts/latest/write_fonts/
pub struct Compilation {
    /// The options passed in for this compilation.
    pub(crate) opts: Opts,
    /// The `head` table, if one was generated
    pub head: Option<wtables::head::Head>,
    /// The `hhea` table, if one was generated
    pub hhea: Option<wtables::hhea::Hhea>,
    /// The `vhea` table, if one was generated
    pub vhea: Option<wtables::vhea::Vhea>,
    /// The `OS/2` table, if one was generated
    pub os2: Option<wtables::os2::Os2>,
    /// The OS/2 builder, preserving which fields were explicitly set in FEA.
    ///
    /// Use this to determine which fields should override computed values:
    /// a field with `Some` was explicitly specified in the FEA source.
    pub os2_builder: Option<super::tables::Os2Builder>,
    /// The `GDEF` table, if one was generated
    pub gdef: Option<wtables::gdef::Gdef>,
    /// The `BASE` table, if one was generated
    pub base: Option<wtables::base::Base>,
    /// The `name` table, if one was generated
    pub name: Option<wtables::name::Name>,
    /// The `STAT` table, if one was generated
    pub stat: Option<wtables::stat::Stat>,
    /// The `GSUB` table, if one was generated
    pub gsub: Option<wtables::gsub::Gsub>,
    /// The `GPOS` table, if one was generated
    pub gpos: Option<wtables::gpos::Gpos>,
    /// Any *explicit* gdef classes declared in the FEA.
    ///
    /// This is provided so that the user can reference them if they are going
    /// to manually generate kerning or markpos lookups.
    pub gdef_classes: Option<HashMap<GlyphId16, GlyphClassDef>>,
    /// Insertion points for generated lookups, keyed by feature tag.
    ///
    /// When a feature block in the FEA source contains a `# Automatic Code`
    /// comment, this records where in the lookup list the generated lookups
    /// should be inserted. This is useful for consumers that emulate generated
    /// features (e.g. kern, mark) and need to know the correct ordering
    /// relative to hand-written feature code.
    pub insert_markers: HashMap<Tag, InsertionPoint>,
    /// Raw bytes for the `Debg` table, present when `Opts::compile_debg` is set.
    ///
    /// The content is UTF-8 JSON compatible with fontTools' feaLib Debg format.
    pub debg: Option<Vec<u8>>,
}

impl PendingCompilation {
    pub(crate) fn has_errors(&self) -> bool {
        self.errors.iter().any(Diagnostic::is_error)
    }

    /// Run the feature provider (if any) and build the final tables.
    ///
    /// This is the second half of [`compile_for_merge`]; call it once, on the
    /// merged result, so that generated features are added a single time.
    ///
    /// [`compile_for_merge`]: crate::compile::compile_for_merge
    pub fn finish<F: FeatureProvider>(
        mut self,
        writer: Option<&F>,
    ) -> Result<(Compilation, DiagnosticSet), DiagnosticSet> {
        let tree = self.tree.clone();
        if let Some(writer) = writer {
            self.run_feature_provider(writer);
        }
        match self.build() {
            Ok((compilation, warnings)) => {
                Ok((compilation, DiagnosticSet::new(warnings, &tree, usize::MAX)))
            }
            Err(errors) => Err(DiagnosticSet::new(errors, &tree, usize::MAX)),
        }
    }

    pub(crate) fn run_feature_provider<T: FeatureProvider>(&mut self, provider: &T) {
        let mut builder = FeatureBuilder::new(
            &self.default_lang_systems,
            &mut self.tables,
            &mut self.mark_filter_sets,
        );
        provider.add_features(&mut builder);
        let mut external_features = builder.finish();

        // we need to register any ConditionSets here, because we want a
        // stable sort order when we compile
        if let Some(conditions) = external_features.feature_variations.as_ref() {
            for conditionset in conditions.conditions.iter().map(|(cs, _)| cs) {
                self.conditionset_defs.register_use(conditionset);
            }
        }
        external_features.merge_into(&mut self.lookups, &mut self.features, &self.insert_markers);
        //we need these for build()
        self.lig_carets_from_feature_writer = external_features.lig_carets;
    }

    /// Infer/update GDEF table as required.
    ///
    /// If a GDEF table is not explicitly defined, we are supposed to create one,
    /// and even if a GDEF table *is* defined, we are supposed to compute certain
    /// of its subtables based on other items encountered in the feature file
    ///
    /// References:
    ///
    /// <http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#4f-markclass>
    /// <http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#9b-gdef-table>
    fn finalize_gdef_table(&mut self) {
        // if the FEA included a GDEF block, use that, otherwise create an empty table
        let mut gdef = self.tables.gdef.take().unwrap_or_default();
        // infer glyph classes, if they were not declared explicitly
        if gdef.glyph_classes.is_empty() {
            gdef.glyph_classes_were_inferred = true;
            self.lookups.infer_glyph_classes(|glyph, class_id| {
                gdef.glyph_classes.insert(glyph, class_id);
            });
            for glyph in self
                .mark_classes
                .values()
                .flat_map(|class| class.members.iter().map(|(cls, _)| cls.iter()))
                .flatten()
            {
                gdef.glyph_classes.insert(glyph, GlyphClassDef::Mark);
            }
        }

        if !self.mark_attach_class_id.is_empty() {
            gdef.mark_attach_class.extend(
                self.mark_attach_class_id
                    .iter()
                    .flat_map(|(cls, id)| cls.iter().map(|gid| (gid, *id))),
            );
        }

        if !self.mark_filter_sets.is_empty() {
            let mut sorted = self
                .mark_filter_sets
                .iter()
                .map(|(cls, id)| (*id, cls.clone()))
                .collect::<Vec<_>>();
            sorted.sort_unstable();
            gdef.mark_glyph_sets = sorted.into_iter().map(|(_, cls)| cls).collect();
        }

        if gdef.ligature_pos.is_empty() {
            gdef.ligature_pos = self.lig_carets_from_feature_writer.clone();
        }

        if !gdef.is_empty() {
            self.tables.gdef = Some(gdef);
        }
    }

    pub(crate) fn build(mut self) -> Result<(Compilation, Vec<Diagnostic>), Vec<Diagnostic>> {
        self.finalize_gdef_table();
        self.features
            .finalize_aalt(&mut self.lookups, &self.default_lang_systems);
        self.features.dedupe_lookups();

        if self.errors.iter().any(Diagnostic::is_error) {
            return Err(self.errors.clone());
        }

        let mut name_builder = self.tables.name.clone();
        let stat = self
            .tables
            .stat
            .as_ref()
            .map(|raw| raw.build(&mut name_builder));

        // the var store builder is required so that variable metrics/anchors
        // in the GPOS table can be collected into an ItemVariationStore
        let mut ivs = VariationStoreBuilder::new(self.axis_count);

        let (mut gsub, mut gpos) = self.lookups.build(&self.features, &mut ivs, &self.opts);
        // if ivs hasn't been used, we don't want to create a GDEF table just for it.
        if !ivs.is_empty() {
            self.tables
                .gdef
                .get_or_insert_with(|| {
                    // If we're creating a new GdefBuilder here, it means
                    // finalize_gdef_table() discarded the previous one because
                    // it was empty. That means no explicit glyph classes were
                    // declared in the FEA, so mark the classes as inferred.
                    // https://github.com/googlefonts/fontc/issues/1847
                    super::tables::GdefBuilder {
                        glyph_classes_were_inferred: true,
                        ..Default::default()
                    }
                })
                .var_store = Some(ivs);
        // but if we _do_ have a gdef table, always add the var store,
        // since we might still add ligature carets to it
        } else if let Some(gdef) = self.tables.gdef.as_mut() {
            gdef.var_store = Some(ivs);
        }

        let (gdef, key_map) = match self.tables.gdef.as_ref().map(|raw| raw.build()) {
            Some((gdef, key_map)) => (Some(gdef), key_map),
            None => (None, None),
        };

        let feature_params = self.features.build_feature_params(&mut name_builder);

        if let Some(gsub) = gsub.as_mut() {
            if let Some(variations) = gsub.feature_variations.as_mut() {
                sort_feature_variations(variations, |condset| {
                    self.conditionset_defs.sort_order(condset)
                });
            }
            for record in gsub.feature_list.feature_records.iter_mut() {
                if let Some(params) = feature_params.get(&record.feature_tag) {
                    record.feature.feature_params = params.clone().into();
                }
            }
        }
        if let Some(gpos) = gpos.as_mut() {
            if let Some(key_map) = key_map {
                // all VariationIndex tables (in value records and anchors)
                // currently have temporary indices; now that we've built the
                // ItemVariationStore we need to go and update them all.
                gpos.remap_variation_indices(&key_map);
            }
            if let Some(variations) = gpos.feature_variations.as_mut() {
                sort_feature_variations(variations, |condset| {
                    self.conditionset_defs.sort_order(condset)
                });
            }

            for record in gpos.feature_list.feature_records.iter_mut() {
                if let Some(params) = feature_params.get(&record.feature_tag) {
                    record.feature.feature_params = params.clone().into();
                }
            }
        }

        let gdef_classes = self.tables.gdef.as_ref().and_then(|gdef| {
            (!gdef.glyph_classes_were_inferred).then(|| gdef.glyph_classes.clone())
        });

        if self.opts.compile_debg {
            let (gsub_info, gpos_info) = self.lookups.debug_info();
            self.tables.debg = Some(super::tables::DebgBuilder::new(
                gsub_info.to_vec(),
                gpos_info.to_vec(),
            ));
        }

        Ok((
            Compilation {
                head: self.tables.head.as_ref().map(|raw| raw.build(None)),
                hhea: self.tables.hhea.clone(),
                vhea: self.tables.vhea.clone(),
                os2: self.tables.os2.as_ref().map(|raw| raw.build()),
                os2_builder: self.tables.os2.clone(),
                gdef,
                base: self.tables.base.as_ref().map(|raw| raw.build()),
                name: name_builder.build(),
                stat,
                gsub,
                gpos,
                opts: self.opts.clone(),
                gdef_classes,
                insert_markers: self.insert_markers.clone(),
                debg: self.tables.debg.as_ref().map(|d| d.build(&self.tree)),
            },
            self.errors.clone(),
        ))
    }
}

impl Compilation {
    /// Returns `true` if the FEA generated tables other than GSUB, GPOS & GDEF.
    pub fn has_non_layout_tables(&self) -> bool {
        self.head.is_some()
            || self.hhea.is_some()
            || self.vhea.is_some()
            || self.os2.is_some()
            || self.base.is_some()
            || self.name.is_some()
            || self.stat.is_some()
            || self.debg.is_some()
    }

    /// Remap any `NameId`s in the name table and anywhere they are referenced.
    ///
    /// This is used for merging the results of our compilation with other
    /// compilation operations which may have occured elsewhere, and which may
    /// have used the same `NameId`s as us for different strings.
    ///
    /// We will take all the name ids we have declared that are >= 256 and offset
    /// them to start at `first_avail_id`.
    pub fn remap_name_ids(&mut self, first_avail_id: u16) {
        let id_offset = first_avail_id.saturating_sub(NameId::LAST_RESERVED_NAME_ID.to_u16() + 1);
        log::info!("remapping FEA name ideas with delta {id_offset}");
        if id_offset == 0 {
            return;
        }

        let adjust_id = |id: NameId| {
            if id == NameId::default() || id.is_reserved() {
                id
            } else {
                // in the case of a degenerate name table we'll just reuse the last id?
                // entries will be pruned later.
                id.checked_add(id_offset)
                    .unwrap_or(NameId::LAST_ALLOWED_NAME_ID)
            }
        };

        if let Some(name) = self.name.as_mut() {
            let records = std::mem::take(&mut name.name_record);
            name.name_record = records
                .into_iter()
                .map(|mut rec| {
                    rec.name_id = adjust_id(rec.name_id);
                    rec
                })
                .collect();
        }

        self.gsub
            .as_mut()
            .into_iter()
            .flat_map(|t| t.feature_list.feature_records.iter_mut())
            .chain(
                self.gpos
                    .as_mut()
                    .into_iter()
                    .flat_map(|t| t.feature_list.feature_records.iter_mut()),
            )
            .for_each(|rec| match rec.feature.as_mut().feature_params.as_mut() {
                Some(FeatureParams::StylisticSet(params)) => {
                    params.ui_name_id = adjust_id(params.ui_name_id);
                }
                Some(FeatureParams::CharacterVariant(params)) => {
                    params.feat_ui_label_name_id = adjust_id(params.feat_ui_label_name_id);
                    params.feat_ui_tooltip_text_name_id =
                        adjust_id(params.feat_ui_tooltip_text_name_id);
                    params.sample_text_name_id = adjust_id(params.sample_text_name_id);
                    params.first_param_ui_label_name_id =
                        adjust_id(params.first_param_ui_label_name_id);
                }
                _ => (),
            });
        if let Some(stat) = self.stat.as_mut() {
            stat.elided_fallback_name_id = stat
                .elided_fallback_name_id
                .map(|id| id.to_u16().saturating_add(id_offset).into());
            stat.design_axes.iter_mut().for_each(|axe| {
                axe.axis_name_id = adjust_id(axe.axis_name_id);
            });
            if let Some(blah) = stat.offset_to_axis_values.as_mut() {
                blah.iter_mut().for_each(|val| match val.as_mut() {
                    AxisValue::Format1(val) => val.value_name_id = adjust_id(val.value_name_id),
                    AxisValue::Format2(val) => val.value_name_id = adjust_id(val.value_name_id),
                    AxisValue::Format3(val) => val.value_name_id = adjust_id(val.value_name_id),
                    AxisValue::Format4(val) => val.value_name_id = adjust_id(val.value_name_id),
                });
            }
        }
    }

    /// Assemble the output tables into a `FontBuilder`.
    ///
    /// This is a convenience method. To compile a binary font you can use
    /// [`to_binary`] instead, and for more fine-grained control you can inspect
    /// and manipulate the raw tables directly.
    ///
    /// [`to_binary`]: Compilation::to_binary
    pub fn to_font_builder(&self) -> Result<FontBuilder<'_>, BuilderError> {
        let mut builder = FontBuilder::default();
        macro_rules! add_if_some {
            ($table:expr_2021) => {
                if let Some(table) = $table.as_ref() {
                    builder.add_table(table)?;
                }
            };
        }
        add_if_some!(self.head);
        add_if_some!(self.hhea);
        add_if_some!(self.vhea);
        add_if_some!(self.os2);
        add_if_some!(self.gdef);
        add_if_some!(self.base);
        add_if_some!(self.name);
        add_if_some!(self.stat);
        add_if_some!(self.gsub);
        add_if_some!(self.gpos);
        if let Some(debg_bytes) = &self.debg {
            builder.add_raw(DEBG_TAG, debg_bytes.as_slice());
        }
        Ok(builder)
    }

    /// Compile the output tables into a font.
    ///
    /// This is a convenience method used for things like testing; if you are
    /// building a font compiler you will probably prefer to manipulate the
    /// generated tables directly.
    pub fn to_binary(&self, glyph_map: &GlyphMap) -> Result<Vec<u8>, BuilderError> {
        // because we often inspect our output with ttx, and ttx fails if maxp is
        // missing, we create a maxp table.
        let mut builder = self.to_font_builder()?;
        let maxp = Maxp::new(glyph_map.len().try_into().unwrap());
        builder.add_table(&maxp)?;
        if self.opts.make_post_table {
            let post = glyph_map.make_post_table();
            builder.add_table(&post)?;
        }

        Ok(builder.build())
    }
}

fn sort_feature_variations(
    variations: &mut FeatureVariations,
    order_fn: impl Fn(&ConditionSet) -> usize,
) {
    variations
        .feature_variation_records
        .sort_by_key(|record| match record.condition_set.as_ref() {
            Some(condition) => order_fn(condition),
            None => order_fn(&Default::default()),
        })
}
