//! Generated by glyphs-reader/data/update.py

use crate::{
    glyphdata::{Category, Subcategory},
    glyphdata_bundled::BundledEntry,
};

impl BundledEntry for Category {
    fn element_size() -> usize {
        1
    }
    fn from_slice(raw: &[u8]) -> Category {
        match raw[0] {
            0 => Category::Letter,
            1 => Category::Mark,
            2 => Category::Number,
            3 => Category::Other,
            4 => Category::Punctuation,
            5 => Category::Separator,
            6 => Category::Space,
            7 => Category::Symbol,
            v => panic!("What is {v}"),
        }
    }
}

/// The subcategory of a given glyph
impl BundledEntry for Option<Subcategory> {
    fn element_size() -> usize {
        1
    }
    fn from_slice(raw: &[u8]) -> Option<Subcategory> {
        match raw[0] {
            0 => Some(Subcategory::Arrow),
            1 => Some(Subcategory::Compatibility),
            2 => Some(Subcategory::Currency),
            3 => Some(Subcategory::Dash),
            4 => Some(Subcategory::DecimalDigit),
            5 => Some(Subcategory::Emoji),
            6 => Some(Subcategory::Enclosing),
            7 => Some(Subcategory::Format),
            8 => Some(Subcategory::Fraction),
            9 => Some(Subcategory::Geometry),
            10 => Some(Subcategory::Halfform),
            11 => Some(Subcategory::Jamo),
            12 => Some(Subcategory::Letter),
            13 => Some(Subcategory::Ligature),
            14 => Some(Subcategory::Math),
            15 => Some(Subcategory::Matra),
            16 => Some(Subcategory::Modifier),
            17 => Some(Subcategory::Nonspacing),
            18 => Some(Subcategory::Number),
            19 => Some(Subcategory::Parenthesis),
            20 => Some(Subcategory::Quote),
            21 => Some(Subcategory::Radical),
            22 => Some(Subcategory::Small),
            23 => Some(Subcategory::Space),
            24 => Some(Subcategory::Spacing),
            25 => Some(Subcategory::SpacingCombining),
            26 => Some(Subcategory::Superscript),
            27 => Some(Subcategory::Syllable),
            255 => None,
            v => panic!("What is {v}"),
        }
    }
}
